server:
  port: 8091

spring:
  spring:
    kafka:
      bootstrap-servers: ${KAFKA_BROKER:localhost:9092}
      topic:
        orchestrator: orchestrator
        payment-validation-sucess: payment-sucess
        payment-validation-fail: payment-fail
      consumer:
        group_id: orchestrator-group
        auto-offset-reset: latest

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5433}/${DB_NAME:payment-db}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  logging:
    level:
      org:
        apache:
          kafka: OFF